// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_88CxtUxEML-WrtoulDCLF0sNzXGJXgA',
    appId: '1:1006835157713:web:c95c7b9c9e22b096f493f0',
    messagingSenderId: '1006835157713',
    projectId: 'push-notifcations-server',
    authDomain: 'push-notifcations-server.firebaseapp.com',
    storageBucket: 'push-notifcations-server.appspot.com',
    measurementId: 'G-8GVBL04PSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2gHRzTDNpy0xiSX3xOSuZZnxfOIBYKVo',
    appId: '1:1006835157713:android:ba57a239402541b4f493f0',
    messagingSenderId: '1006835157713',
    projectId: 'push-notifcations-server',
    storageBucket: 'push-notifcations-server.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH4aHxnLJBeAWGG5egnKGSaTcyeiHn_60',
    appId: '1:1006835157713:ios:9a7b904cf5ceb86ff493f0',
    messagingSenderId: '1006835157713',
    projectId: 'push-notifcations-server',
    storageBucket: 'push-notifcations-server.appspot.com',
    iosClientId: '1006835157713-dvt8rng44018cv08uibmlhmakvtgrr84.apps.googleusercontent.com',
    iosBundleId: 'com.example.estcProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH4aHxnLJBeAWGG5egnKGSaTcyeiHn_60',
    appId: '1:1006835157713:ios:9a7b904cf5ceb86ff493f0',
    messagingSenderId: '1006835157713',
    projectId: 'push-notifcations-server',
    storageBucket: 'push-notifcations-server.appspot.com',
    iosClientId: '1006835157713-dvt8rng44018cv08uibmlhmakvtgrr84.apps.googleusercontent.com',
    iosBundleId: 'com.example.estcProject',
  );
}
